/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTestsRouteImport } from './routes/dashboard.tests'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardModernizeRouteImport } from './routes/dashboard.modernize'
import { Route as DasboardArchitectureRouteImport } from './routes/dasboard.architecture'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestsRoute = DashboardTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardModernizeRoute = DashboardModernizeRouteImport.update({
  id: '/modernize',
  path: '/modernize',
  getParentRoute: () => DashboardRoute,
} as any)
const DasboardArchitectureRoute = DasboardArchitectureRouteImport.update({
  id: '/dasboard/architecture',
  path: '/dasboard/architecture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dasboard/architecture': typeof DasboardArchitectureRoute
  '/dashboard/modernize': typeof DashboardModernizeRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/tests': typeof DashboardTestsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dasboard/architecture': typeof DasboardArchitectureRoute
  '/dashboard/modernize': typeof DashboardModernizeRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/tests': typeof DashboardTestsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dasboard/architecture': typeof DasboardArchitectureRoute
  '/dashboard/modernize': typeof DashboardModernizeRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/tests': typeof DashboardTestsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dasboard/architecture'
    | '/dashboard/modernize'
    | '/dashboard/security'
    | '/dashboard/tests'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dasboard/architecture'
    | '/dashboard/modernize'
    | '/dashboard/security'
    | '/dashboard/tests'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dasboard/architecture'
    | '/dashboard/modernize'
    | '/dashboard/security'
    | '/dashboard/tests'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DasboardArchitectureRoute: typeof DasboardArchitectureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tests': {
      id: '/dashboard/tests'
      path: '/tests'
      fullPath: '/dashboard/tests'
      preLoaderRoute: typeof DashboardTestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/modernize': {
      id: '/dashboard/modernize'
      path: '/modernize'
      fullPath: '/dashboard/modernize'
      preLoaderRoute: typeof DashboardModernizeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dasboard/architecture': {
      id: '/dasboard/architecture'
      path: '/dasboard/architecture'
      fullPath: '/dasboard/architecture'
      preLoaderRoute: typeof DasboardArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardModernizeRoute: typeof DashboardModernizeRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardTestsRoute: typeof DashboardTestsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardModernizeRoute: DashboardModernizeRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardTestsRoute: DashboardTestsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DasboardArchitectureRoute: DasboardArchitectureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
